repos:
  - repo: local
    hooks:
      - id: alejandra
        name: Alejandra Nix Formatter
        entry: alejandra
        language: system
        files: '\.nix$'
        pass_filenames: true
        
      - id: nixpkgs-fmt
        name: Nixpkgs-fmt Nix Formatter
        entry: nix-shell -p nixpkgs-fmt --run "nixpkgs-fmt"
        language: system
        files: '\.nix$'
        pass_filenames: true
        
      - id: nix-flake-check
        name: Nix Flake Check
        entry: nix flake check
        language: system
        pass_filenames: false
        always_run: true
        
      - id: nix-instantiate
        name: Nix Instantiate
        entry: bash -c 'find . -name "*.nix" -not -path "./.git/*" -not -name "flake.nix" -not -name "configuration.nix" -exec nix-instantiate --parse {} \;'
        language: system
        pass_filenames: false
        always_run: true
        
      - id: shellcheck
        name: Shellcheck
        entry: shellcheck
        language: system
        types: [shell]
        exclude: '^tests/'
        
      - id: test-suite
        name: Run Test Suite
        entry: bash tests/run-all-tests.sh
        language: system
        pass_filenames: false
        always_run: true
        stages: [push]