# Hardware configuration for minimal-zfs
# This will be generated by nixos-generate-config
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # This will be populated by the installer
  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # Filesystems are defined by disko in disko.nix
  # Only define filesystem settings that disko doesn't handle

  swapDevices = [ ];

  hardware.enableRedistributableFirmware = true;
}